In [61]:
import pandas as pd

df = pd.read_csv('/content/startup_funding.csv')
df.columns

Index(['Sr No', 'Date dd/mm/yyyy', 'Startup Name', 'Industry Vertical',
       'SubVertical', 'City  Location', 'Investors Name', 'InvestmentnType',
       'Amount in USD', 'Remarks'],
      dtype='object')

In [62]:
df['Startup Name'].unique().tolist()

['BYJU’S',
 'Shuttl',
 'Mamaearth',
 'https://www.wealthbucket.in/',
 'Fashor',
 'Pando',
 'Zomato',
 'Ecozen',
 'CarDekho',
 'Dhruva Space',
 'Rivigo',
 'Healthians',
 'Licious',
 'InCred',
 'Trell',
 'Rein Games',
 'Lenskart.com',
 'Freshworks',
 'Misters',
 'Sunstone Eduversity Pvt. Ltd',
 'Burger Singh',
 'Ninjacart',
 'Aye Finance',
 'SuperGaming',
 'Clumio',
 'eBikeGo',
 'Digital Mall Asia',
 'Medikabazaar',
 'Vogo Automotive',
 'Furtados School of Music',
 'Paytm',
 'Dunzo',
 'Udaan',
 'The Man Company',
 'FPL Technologies',
 'Cashflo',
 'Digital F5',
 '3rdFlix',
 '75F',
 'Myelin Foundry',
 'Atomberg Technology',
 'GOQii',
 'Vyapar App',
 'Progcap',
 'MyPetrolPump',
 'Alteria Capital',
 'Pine Labs',
 'Meesho',
 'Cars24',
 'Uniphore',
 'Zendrive',
 'Lo! Foods',
 'Tala',
 'INDwealth',
 'HungerBox',
 'AdmitKard',
 'Mishry Reviews',
 'Grofers',
 'Rapido Bike Taxi',
 'RenewBuy',
 'Atlan',
 'WizCounsel',
 'Ola Cabs',
 'Daalchini Technologies',
 '"BYJU\\\\\'S"',
 'Moglix',
 'Ezyhaul',
 'Indus OS',
 'HealthAssure',
 'House of Msasaba',
 'Board Infinity',
 'NoBroker',
 'Bira91',
 'FabHotels',
 'Avail Finance',
 'BharatPe',
 'Recykal',
 'Agara Labs',
 'Sistema.bio',
 'Chakr Innovation',
 'Pratilipi',
 'Bolo App',
 'OkCredit',
 'Biz2Credit',
 'Vogo Automotive Pvt. Ltd.',
 'Leegality',
 'Ola Electric',
 'Saahas Zero Waste',
 'StyleDotMe',
 'BlackBuck',
 'Zenoti',
 'Ather Energy',
 'FreshVnF',
 'GlowRoad',
 'Kuvera',
 'Medlife',
 'Kabadiwala',
 'Tripoto',
 'Azah',
 'Setu',
 'Toppr',
 'Craftsvilla',
 'Unacademy',
 'CleverTap',
 'My Healthcare',
 'KrazyBee',
 'Increff',
 'FleetX',
 'Zilingo',
 'NanoClean Global',
 'OyoRooms',
 'Vyome Therapeutics Inc.',
 'Samunnati Financial Intermediation & Services Pvt. Ltd',
 'Manch',
 'UrbanClap Technologies Pvt. Ltd',
 'Guiddoo',
 'Career Anna',
 'Nagpur Wholesale',
 'ShopKirana',
 'BuildSupply',
 'GoDesi',
 'Veritas Finance Ltd.',
 'Mobile Premier League',
 'A&R Bon Vivants',
 'Blackbuck',
 'MilkBAsket',
 'DriveU',
 'CleanseCar',
 'Automation Anywhere',
 'HealthifyMe',
 'Genius Corner',
 'Aavishkaar-Intellecap Group',
 'Skillbox',
 'Signzy',
 'Engineer.ai',
 'InCred Finance',
 'Roposo',
 'Northmist',
 'Origo Commodities India Pvt. Ltd',
 'Grover Zampa',
 'Droom',
 'Innov8',
 'LetsTransport',
 'Netmeds',
 'Daily hunt',
 '3HCare',
 'HappyGoEasy',
 'Nykaa',
 'Mad Street Den',
 'Dream11',
 'MamaEarth',
 'AutoGrid',
 'Pharmeasy',
 'Upwards',
 'Kissht',
 'dishq',
 'HealthFin',
 'Samosa Labs',
 'ZiffyHomes',
 'My OmNamo',
 'ShopX',
 'MakeMyTrip',
 'Hansel io',
 'Metro Bikes',
 'Phone Pe',
 'quizizz',
 'Happy EMI',
 'Inthree',
 'Observe AI',
 'Enakshi',
 'EazyDiner',
 'Finzy',
 'RawPressery',
 'Pi Ventures',
 'Revv',
 'ZestMoney',
 'Shubh Loans',
 'MyUpchar',
 'Narvar',
 'True North',
 'Leena AI',
 'Biryani By Kilo',
 'Anchanto',
 'Loan Tap',
 'PolicyBazaar',
 'zippserv',
 'Groww',
 'Avenue Growth',
 'iNICU',
 'Kinara Capital',
 'Shop 101',
 'Sambandh',
 '19th mile',
 '5th Vital',
 'MEngage',
 'Ofbusiness',
 'The Ken',
 'Book My Show',
 'HousingMan',
 'PaySense',
 'Yulu Bikes',
 'VTION',
 'Log9 Materials',
 'kidovators',
 'Digit',
 'Black Soil',
 'iqlect',
 'Entropik',
 'Bitla Software',
 'TheCapitalNet',
 'Cure Fit',
 'Five Star Group',
 'Healthsignz',
 'CoinTribe',
 'Digiconectt',
 'Kashmir Box',
 'Crowdera',
 'Zoctr',
 'Annapurna Finance',
 'AyeFinance',
 'Theranosis',
 'Alpha Capital',
 'eshakti',
 'Daily Ninja',
 'NirogStreet',
 'Nivesh',
 'What\\\\xe2\\\\x80\\\\x99s Up Life',
 'HomeLane',
 'Network Intelligence',
 'Tynor Othontics',
 'Elucidata',
 'Chrysalis',
 'RentSher',
 'Drip capital',
 'WickedRide',
 'HipBar',
 'Sqqrl',
 'Sigtuple',
 'Wow Express',
 'Front Desk AI',
 'Edureka',
 'Numeroseven',
 'OpenTap',
 'Bizongo',
 'Disprz',
 'PaisaDukan',
 'i3sysytems',
 'Earth Food',
 'mfine',
 'Rocketium',
 'MilkBasket',
 'Vola',
 'Cashkumar',
 'Edyoo',
 'Aashiyaan',
 'Smartivity',
 'Bonphulapl',
 'Acko',
 'HWell24',
 'Toffee',
 'Tonetag',
 'Events High',
 'Stellaps',
 'Credright',
 'Fitternity',
 'Synctag',
 'Benepik',
 'Varthana',
 'IndigoLearn',
 'Vedantu',
 'Kaleidofin',
 'Pipabella',
 'Elemential',
 'Kriger Campus',
 'Loanzen',
 'TravelTriangle',
 'Letsmd',
 'mintifi',
 'icanstay',
 'Pregbuddy',
 'Coverfox',
 'Lenskart',
 'mamaearth',
 'Fyle Technologies',
 'True Balance',
 'Visit',
 'Doxper',
 'Mihuru',
 'Capital Float',
 'Trip shelf',
 'POPxo',
 'RailYatri',
 '1mg',
 'Rubique',
 'Samco',
 'MyLoanCare',
 'PharmEasy',
 'Buddy4studdy',
 'Urban Ladder',
 'Gramophone',
 'Wellthy',
 'MedGenome',
 'Finova Capital',
 'Hotelogix',
 'Livehealth',
 'Ad2pro',
 'Pepperfry',
 'Magicpin',
 'HealthCare',
 'PineLabs',
 'Stumagz',
 'AvailFinance',
 'Fingerlix',
 'Karma Healthcare',
 'Zappfresh',
 'CustomerSucessBox',
 'One Labs',
 'GigIndia',
 'Chargebee',
 'i2i Funding',
 'Slang Labs',
 'UrbanPiper',
 'Cash Suvidha',
 'Roadcast',
 'Smartcoin',
 'The Print',
 'Fynd',
 'BigBasket',
 'Asia Institute Of Medical Science',
 'CollegeDekho',
 'Foodmemories',
 'Healthi',
 'Swiggy',
 'Shape',
 'Icertis',
 'healthifyme',
 'MedTel',
 'Rupeek',
 'WebEngage',
 'Lendingkart',
 'Wydr',
 'Cashify',
 'holachef',
 'Awaaz De',
 'IMAX Program',
 'Littlemore',
 'Shirsa Labs',
 'MoneyOnMobile',
 'PetSutra',
 'Infibeam',
 'happay',
 'Fincash',
 'Agricxlab',
 'Capillary',
 'The Healthy Billions',
 'HighRadius',
 'Avishkaar Box',
 'Planys Technologies',
 'Lollypop',
 'Trilyo',
 'Gaana',
 'Credy',
 'Predible Health',
 'EarlySalary',
 'WOTU',
 'DAAKI',
 'Kinsane Entertainment Inc',
 'Tapzo',
 'Appario Retail Pvt Ltd.',
 'Samunnati',
 'Sahajanand Medical Technologies',
 'Kuants',
 'Razorpay',
 'Streak',
 'pi Ventures',
 'Newgen Software',
 'Rubix',
 'ShareChat',
 'Paperflite',
 'Skillate',
 'OptaCredit',
 'AEON Learning',
 'Milkbasket',
 'NeoGrowth Credit',
 'Rao IIT Academy',
 'Glassic',
 'GreyAtom',
 'Axio',
 'eKincare',
 'The Wedding Brigade',
 'PeeSafe',
 'BrowserStack',
 'Scapic',
 'CureFit',
 'iNurture',
 'Strata Enviro',
 'Tata Housing',
 'HandyTrain',
 'Mobycy',
 'Greenlight Planet',
 'Fintobox',
 'Mswipe',
 'The Label Life',
 'Cygnus Hospitals',
 'eShakti',
 'Inshorts',
 'Vahdam Tea',
 'Logic Roots',
 'Project Mudra',
 'Furlenco',
 'I Can Stay',
 'Fracktal Works',
 'Simility',
 'Shopholix',
 'MindTickle',
 'Nazara Technologies',
 'DocsApp',
 'Capita World',
 'Tea Box',
 'Transversal Technologies',
 'Curofy',
 'WeDoSky',
 'Purplle',
 'Sky Met Weather',
 'Springboard',
 'Peel Works',
 '9Stacks',
 'Your Quote',
 'Spandana Sphoorty',
 'EasyEcom',
 'IGP.com',
 'Specsmakers',
 'Garage On Road',
 'Foyr.com',
 'Prest Loans',
 'AadharAPI.com',
 'FreshBoxx',
 'Vagupu',
 'HalaPlay',
 'Kalpnik Technologies',
 'Hevo Data',
 'Smart Karma',
 'Leverage Edu',
 'Crayon Data',
 'DocTalk',
 'CoveIoT',
 'TalentEdge',
 'Fisdom',
 'FarmLink',
 'OpenApp',
 'NoPaperForms',
 'Tilite Technologies Pvt. Ltd',
 'Mobiliz AR',
 'Qubole',
 'Happily Unmarried',
 'Universal Sportsbiz Pvt. Ltd',
 'Hungry Foal',
 'Active AI',
 'Sumeru',
 'ElderAid Wellness',
 'Omnia Information',
 'Josh Talks',
 'Reniso',
 'Kanhaiya',
 'Perspectico',
 'ONN Bikes',
 'Rapido',
 'Heckyl',
 'Nuvepro',
 'RedBook',
 'Portea',
 'Credit Mate',
 'Epiq Capital',
 'MiStay',
 'WittyFeed',
 'IDG Ventures',
 'TempGo',
 'Edelweiss',
 'ERA',
 'Smaaash',
 'Chumbak',
 'FR8',
 'MobieFit',
 'Stanza Living',
 'ChqBook',
 'HomeCapital',
 'Elanic',
 'CollPoll',
 'PhonePe',
 'Little Black Book',
 'Oorjan',
 'Zefo',
 'Yaantra',
 'Farm Taaza',
 'Drivezy',
 'Slice Pay',
 'Agrowave',
 'MyGubbi',
 'IBSFintech',
 'Letsservice',
 'OneStepUp',
 'ThirdWatch',
 'Parallel Dots',
 'Easy Diner',
 'StanPlus',
 'UCLID',
 'Policy Bazaar',
 'Gapoon',
 'Chaayos',
 'Renew Buy',
 'Bank Bazaar',
 'Hasura',
 'LenDen Club',
 'RAW Pressery',
 'Cashe',
 'Park Easy',
 'TagBox',
 'FYRE',
 'ZipLoan',
 'Skillenza',
 'Chevon',
 'PropStory',
 'SpotDraft',
 'Big Basket',
 'OfBusiness',
 'Olly Credit',
 'CashFree',
 'GoldFarm',
 'NetMeds',
 'MSE',
 'Aahaa Stores',
 'MFine',
 'Canvera',
 'PrimaryIO',
 'Nest Education',
 'Lending Kart',
 'GoFro',
 'OncoStem',
 'Power2SME',
 'Credit Vidya',
 'Tails Life',
 'OYO Rooms',
 'Early Salary',
 'Seniority',
 'AYE Finance',
 'Farmizen',
 'Ecom Express',
 'Call Health',
 'Sattviko',
 'Tonbo Imaging',
 'Get My Parking',
 'Glowroad',
 'Heterogenous',
 'Gurukul',
 'WheelStreet',
 'Xprep',
 'The Moms Co',
 'Noticeboard',
 'High Radius',
 'HWell24 Plus',
 'SaveBC',
 'Gaming Monk',
 '91SpringBoard',
 'Homergize',
 'Yatra.com',
 'Ace Turtle',
 'Vogo',
 'Synup',
 'Tinmen',
 'Cropin',
 'Sportobuddy',
 'Credifiable',
 'Inclov',
 'Multibhashi',
 'Transerve',
 'Fashalot',
 'Pitstop',
 'GoChoppers',
 'Aadyah',
 'TouchKin',
 'Ethinos',
 'Zepo',
 'Click2Clinic',
 'SpeedBox',
 'Skill Connect',
 'Chai Point',
 'Lime Tray',
 'CoutLoot',
 'Box My Space',
 'Curatio',
 'New Castle Technologies',
 'My Forex Eye',
 'TruxApp',
 'CroFarm',
 'DoodhWala',
 'Stayabode',
 'Flipkart',
 'Moong Labs',
 'Sports Flashes',
 'Digilend',
 'KNAB Finance',
 'Get Simpl',
 'Rootefy',
 'Cerebroz',
 'Flochat',
 'EasyGov',
 'Milk Basket',
 'Dhruva',
 'Bombay Shaving Company',
 'Awign',
 'Indiez',
 'Ezetap',
 'Ink Monk',
 'Medinfi',
 'Mobikon',
 'Fieldassist',
 'Treebo',
 'Billion Loans',
 'Ecolibriumenergy',
 'Jumbotail',
 'Timesaverz',
 'Minjar',
 'MyCity4kids',
 'Clip App',
 'Upwardly.in',
 'Autorox.co',
 'Fabogo',
 'Flickstree',
 'Design Cafe',
 'Innoviti',
 'VDeliver',
 'Bottr.me',
 'Arcatron',
 'QwikSpec',
 'Vayana',
 'MObiquest',
 'Ambee',
 'Ideal Insurance',
 'Hypernova Interactive',
 'Rentomojo',
 'AirCTO',
 'Playablo',
 'Trupay',
 'Brick2Wall',
 'FableStreet',
 'Monsoon Fintech',
 'MonkeyBox',
 'Byju\\\\xe2\\\\x80\\\\x99s',
 'Creator\\\\xe2\\\\x80\\\\x99s Gurukul',
 'Fab Hotels',
 'ThinkerBell',
 'Jhakaas',
 'BigStylist',
 'Gympik.com',
 'Tripeur',
 'RentOnGo',
 'Goomo',
 'MaxMyWealth',
 'Spinny',
 'Healthbuds',
 'Ftcash',
 'BHIVE Workspace',
 'wayForward',
 'GyanDhan',
 'GrowFitter',
 'Stratfit',
 'Multiplier Solutions',
 'ABI Health',
 'Stockal',
 'Guidoo',
 'eSahai.in',
 'Loanmeet',
 'LendingKart',
 'Boxx.ai',
 'PeeSafe.in',
 'Vista Rooms',
 'CoverFox',
 'HyperTrack',
 'Goodera',
 'Ola',
 'Vanitycask',
 'MrNeeds',
 'MoneyTap',
 'Goodbox',
 'PortDesk',
 'EdgeFx',
 'HealthIntel',
 'Unbxd',
 'DarwinBox',
 'ForeverShop',
 'Insider.in',
 'Grow Fit',
 'Fabulyst',
 'mSwipe',
 'OneAssist',
 'Julia Computing',
 'Explore Life traveling',
 'Loantap',
 'Voxweb',
 'HUG Innovations',
 'V Resorts',
 'Stashfin',
 'Formcept',
 'Spares Hub',
 'FiTraQ',
 'Niki.ai',
 'Fitpass',
 'ZingHR',
 'Tagos Design',
 'UrbanClap',
 'Ace2three',
 'Innovapptive',
 '4tigo',
 'SMECorner',
 'ZippServe',
 'HealthMir',
 'Uactive',
 'i-lend',
 'Good Methods Global',
 'Balance App',
 'YepMe',
 'Nightstay',
 'Devourin',
 'MyGreens',
 'Curie Labs',
 'Uncanny Vision',
 'Sequretek',
 'Lucideus',
 'Vidooly',
 'Shopclues',
 'Fourth Ambit',
 'Chymera VR',
 'Book My Diamond',
 'ION Energy',
 'Legal Raasta',
 'Log 9 Materials',
 'Remit Guru',
 'Aequm',
 'Zapty',
 'Vernacular.ai',
 'Telr',
 'Genie',
 'Paysense',
 'The Good Life',
 'PumpKart',
 'EzCred',
 'HealthSutra',
 'Delhivery',
 'ZipGrid',
 'TravelSpice',
 'Box8',
 'GenNext Students',
 'WhatsLoan',
 'Cube Consumer Services',
 'Wowflux',
 'Collateral Medical',
 'Loadshare',
 'SimpliLend',
 'Supr Daily',
 'SastaSundar',
 'Eruditus',
 'TestBook',
 'Healthcare at Home',
 'Tyre Express',
 'SmartCoin',
 'WayCool',
 'Perfios',
 'Whatfix',
 'ElastiRun',
 'Trukky',
 'Konsult App',
 'Credit Sudhaar',
 'DataWeave',
 'Medwell Ventures',
 'Mech Mocha',
 'Startup Buddy',
 'QorQI',
 'Twenty Two Motors',
 'WonderChef',
 'FastFox',
 'Omnify',
 'MergerWare',
 'Clovia',
 'Emiza',
 'HackerEarth',
 'Squadrun',
 'ScoutMyTrip',
 'SafetyKart',
 'WeAreHolidays',
 'Myly',
 'CrediHealth',
 'Navia Life Care',
 'Raw Pressery',
 'Snackible',
 'Be U Salons',
 'Simulanis',
 'Innefu Security Consulting',
 'Whodat',
 'Absentia VR',
 'IOTrek',
 'HolaChef',
 'Wooplr',
 'Video Ken',
 'Faasos',
 'Oyo Rooms',
 'Niramai',
 'The Office Pass',
 'Awfis',
 'Myra',
 'Flytxt',
 'Howdy Ventures',
 'StalkBuyLove',
 'ZipGo',
 'Scootsy',
 'Autobix',
 'eShiksha',
 'Sepalika',
 'Mintwalk',
 'Qriyo',
 'Belong',
 'Seenit',
 'Paalak',
 'Celes Care',
 'Karomi',
 'Red Carpet',
 'Kreate Konnect',
 'CreditMantri',
 'Lets Endorse',
 'Tydy',
 'Nactus',
 'Oho Shop',
 'Emojifi',
 'Paytm Marketplace',
 'iGenetics',
 'Juno Clinic',
 'Summerlabel',
 'PickMe',
 'Agrostar',
 'Zapr',
 'Data Resolve',
 'Book Servicing',
 'Blowhorn',
 'PipeCandy',
 'Parentune',
 'AppBrowzer',
 'MagicBricks',
 'PeeBuddy',
 'iOrderFresh',
 'Lavelle Networks',
 'PropertyShare',
 'MyDermacy',
 'LatestOne',
 'Frapperz',
 'mPaani',
 'ShilpMIS',
 'Fitso',
 'FarMart',
 'Airpay',
 'MyGlamm',
 'The Mons Co.',
 'Haqdarshak',
 'Ixigo',
 'Markets and Markets',
 'Bizom',
 'BabyonBoard',
 'Sport Flashes',
 'Wigzo',
 'DoneThing',
 'Zapyle',
 'Ithaka',
 'perpule',
 'Emflux Motors',
 'Klinic App',
 'Oriano Solar',
 'Rooter',
 'FalconBrick',
 'Clodura',
 'Stockroom.io',
 'iManageMyHotel',
 'Inner Hour',
 'Travel Triangle',
 'Wandertrails',
 'Zenatix',
 'Cartrade',
 'MindYourFleet',
 'Edurev',
 'Voonik',
 '1Crowd',
 '48East',
 'Redesyn',
 'Flutura',
 'Wassup',
 'Better Mortgage',
 'Nurturey',
 'Fyle',
 'GoBumpr',
 'CCAvenue',
 'Connaizen',
 'AirZaar',
 'Truebil',
 'YourStory',
 'Imaginate',
 'Aisle',
 'TownScript',
 'Leopetra',
 'Blood n Care',
 'Vebbler',
 'Lets Reap',
 'Oglas',
 'Staydobe',
 'Johari Shop',
 'NeoStencil',
 'TaxSutra',
 'TempoGo',
 'GoFynd',
 'Vow Car Clinic',
 'LearnTron',
 'MobiDent',
 'Yostra',
 'Leap India',
 'FreeCharge',
 'TicketNew',
 'Intelligence Node',
 'Securens',
 'Loan Frame',
 'DriveSkool',
 'LensKart',
 'InstaOffice',
 'Hansel.io',
 'Square Yards',
 'Roambee',
 'PaisaWapas',
 'iService',
 'SecururAX',
 'Leadburg',
 'ZoloStays',
 'Oi Media',
 'HipCouch',
 'Curiositi',
 'TinyStep',
 'Practo',
 'Ketchupp',
 'Hoopy',
 'Ezytruk',
 'Kratikal',
 'Direct Create',
 'Vahdam Teas',
 'Qwikspec',
 'PParke',
 'Weddingz.in',
 'Native Special',
 'Fitnapp',
 'Ethosh',
 'MessaGif',
 'SmartHi',
 'CRON Systems',
 'CueMath',
 'ChipperSage',
 'SelectJobs',
 'Khel Now',
 'NowFloats',
 'Lets Transport',
 'BetaOut',
 'Wishberry',
 'RML Agtech',
 'LoyaltyPrime',
 'InstaSafe',
 '99Games',
 'AirMed Labs',
 '99PerHour',
 'Kochi Post',
 'Intuit Things',
 'Cloudrino',
 'FabX',
 'Maptags',
 'YOLO Health',
 'Heads Up For Tails',
 'Register My Marriage',
 'SidQam',
 'India Lends',
 'Slide App',
 'Badiyajobs',
 'Streo',
 'TYGR',
 'Mr Hot Foods',
 'UrDoorStep',
 'Diro Labs',
 'THB',
 'LookAtMe',
 'Netree',
 'BookEventz',
 'Tailslife',
 'WealthApp',
 'Vehico',
 'Zest Money',
 'GoMechanic',
 'Stalk Buy Love',
 'Wittyparot',
 'NeuroEquilibrium',
 'Xseed Education',
 ...]

In [63]:
sorted(df['Investors Name'].fillna('Unknown').unique().tolist())

['"Kedaraa Capital, Ontario Teachers\\\\\'"',
 '021 Capita, Binny Bansal',
 '1Crowd',
 '1Crowd (through crowd funding)',
 '1Crowd (through crowdfunding)',
 '1Crowd, Ankur Capital',
 '1Crowd, Eureka Forbes Ltd, Shapoorji Pallonji & Co. Ltd.',
 '3 undisclosed HNIs',
 '3 undisclosed investors',
 '3One4 Capital',
 '3one4 Capital, Mumbai Angels, Aarin Capital',
 '3one4 Capital, Tracxn Labs, Aaruha Technology Fund, Endiya Partners',
 '3one4 capital',
 '500 Startups',
 '500 Startups, IDG Ventures & Advantedge fund, Neeraj Arora, Leon Seynave',
 '500 Startups, IvyCap Ventures',
 '500 Startups, Littlerock, Singularity Ventures',
 '500 Startups, Mato Peric & Others',
 '500 Startups, Mato Peric, TracxnLabs',
 '500 Startups, Purvi Capital, Rajan Anandan, Abhishek Gupta',
 '500 Startups, Smile Multimedia, Kunal Bahl, Rohit Bansal, Girish Matrubootham',
 '500 Startups, TV Mohandas Pai, Tandem Capital, Vikram Chachra, Aloke Bajpai',
 '50K Ventures',
 '50k Ventures, Munish Jauhar, Pulkit Jain, Rohit Narang',
 '91maker.com',
 'A M Sikander',
 'A91 Partners',
 'AB Kinnevik, Falcon Edge Capital, Coatue Management',
 'ABI-Showatech (India) Ltd',
 'ABM Knowledgeware',
 'ADAG Reliance Private Equity',
 'AJ Ventures and Jain International Trade Organisation (JITO)',
 'ANALEC',
 'ANI Technologies Pvt. Ltd',
 'APIS Partners',
 'ASK Pravi',
 'AV Thomas Group',
 'AVG Group, 500 Startups',
 'Aakrit Vaish, Swapan Rajdev, Sushill Jiwarajka',
 'Aamir Khan',
 'Aarin Capital',
 'Aarin Capital Partners',
 'Aarin Capital Partners,',
 'Aarin Capital Partners, TV Mohandas Pai',
 'Aarin Capital, Michael Herzig, Ashish Lakhanpal',
 'Aarin Capital, Unitus Seed Fund',
 'Aarti Group',
 'Aavishkaar',
 'Aavishkaar Venture Management',
 'Aavya Ventures',
 'Abhijit Avasthi, Karan Chellani, SP Vijay',
 'Abhinav Bindra, Gaurav Marya',
 'Abhinav Gupta,',
 'Abhinav Mathur',
 'Abhishek Agarwal, Krishnakumar Nataraj, Sarath Sura, Shanti Mohan, Sarthak and Nihit Agarwal, Suramya Gupta',
 'Abhishek Bhatewara, Vivek Shah, Haitong Securities, Suraj Saharan, Paras Arora',
 'Abhishek Gupta',
 'Abraaj Group',
 'Accel (formerly known as Accel Partners)',
 'Accel Partner, Jungle Ventures',
 'Accel Partners',
 'Accel Partners India',
 'Accel Partners India, RB Investments',
 'Accel Partners,',
 'Accel Partners, Anupam Mittal & other marquee investors',
 'Accel Partners, Ashish Hemrajani, Parikshit Dar, Rajesh Balpande',
 'Accel Partners, Beenext, Powerhouse Ventures, Akusa Holdings',
 'Accel Partners, Deep Kalra, Rajesh Magow, Mohit Gupta, Shamik Sharma',
 'Accel Partners, Elevar Equity, Pramod Bhasin, Rajan Anandan, Gaurav Dalmia, Abhishek Goyal, Gagan Hasteer , Arun Tadanki',
 'Accel Partners, Exfinity Ventures, Partech Ventures',
 'Accel Partners, Flipkart',
 'Accel Partners, Helion Venture Partners',
 'Accel Partners, IDG Venture, Endiya Partners, pi Ventures, VH Capital, Axilor Ventures and Binny Bansal',
 'Accel Partners, IDG Ventures India',
 'Accel Partners, IDG Ventures, Endiya Partners, pi Ventures, VH Capital, Axilor Partners',
 'Accel Partners, IDG Ventures, Kalaari Capital',
 'Accel Partners, IDG Ventures, Kalaari Capital,\\\\xc2\\\\xa0 UC-RNT fund',
 'Accel Partners, Indian Angel Network, India Innovation Fund India Venture Partners',
 'Accel Partners, International Finance Corporation (IFC), Qualcomm Ventures, Ventureast',
 'Accel Partners, Jungle Ventures, SeedPlus',
 'Accel Partners, Kalaari Capital',
 'Accel Partners, Matrix Partners, Girish Mathrubootham',
 'Accel Partners, Nandan Nilekani,',
 'Accel Partners, Nandan Nilekani\\\\xe2\\\\x80\\\\x99s NRJN Trust, Mistletoe, Qualcomm Ventures, M&S Partners',
 'Accel Partners, Qualcomm Ventures, M&S Partners, Zop Smart',
 'Accel Partners, RB Investments',
 'Accel Partners, SAIF Partners',
 'Accel Partners, Sequoia Capital',
 'Accel Partners, Sequoia Capital, RB Investments',
 'Accel Partners, Sequoia India, Y Combinator and others.',
 'Accel Partners, Shunwei Capital',
 'Accel Partners, Subrata Mitra, Larry Braitman, Venk Krishna',
 'Accel Partners, Tiger Global And Others',
 'Accel Partners, Tiger Global Management',
 'Accel Partners, Traxcn Labs & Others',
 'Accel Partners, Zephyr Peacock',
 'Accel US, Accel India, SAIF Partners.',
 'Accion Venture Lab, Unicorn India Ventures and ISME ACE.',
 'Accion Venture Lab, YourNest Venture Capital And Other Angel Investors',
 'Accion Venture Labs, Rianta Capital',
 'Accion, LeapFrog Investments, Lok Capital',
 'Ackermans & van Haaren, HealthQuad, Rebright Partners, Toppan Printing',
 'Actis, Altimeter Capital',
 'Acumen Fund',
 'Adroitent Pvt. Ltd.',
 'AdvantEdge',
 'Aegon NV',
 'Aequs Group',
 'Agarwal Movers Group',
 'Agnus Capital',
 'Agnus Capital, Khattar Holdings',
 'Ah! Ventures, Calcutta Angels,\\\\xc2\\\\xa0 91SpringBoard',
 'Ajai Chowdhry, Ashvin Chadha, Yogesh Bansal,\\\\nNitin Singhal & Others',
 'Ajay Data & other HNIs',
 'Ajay Data & undisclosed HNIs',
 'Ajay Nanavati, Afsal Salu',
 'Ajay Piramal',
 'Ajay Relan',
 'Ajay Relan and Vinay Mittal',
 'Ajay Relan,',
 'Ajay Relan, LetsVenture',
 'Ajeet Khurana & Others',
 'Ajeet Khurana Jinesh Shah, Vikram Chachra, Dr. Aniruddha Malpani',
 'Ajit Surana, Sanjay Mehta',
 'Ajith Nair',
 'Ajith Nair, Anish K',
 'Ajith Sukumaran, Currae Healthtech Fund',
 'Ajmera Group of Companies',
 'Al Dhaheri family',
 'Alex Chua, Rahul Garg',
 'Alex Kuruvilla, Pradeep Guha, Saket Dhankar, Rajan Pandhare',
 'Alibaba',
 'Alibaba Group, Ant Financial',
 'Alibaba Pictures',
 'Alibaba, Foxconn, Softbank',
 'Alibaba, Helion Venture Partners, Bessemer Venture Partners, Ascent Capital',
 'Allcargo Logistics, Navneet Education and Mahavir Agency',
 'Allen Blue, John Katzman, Naveen Tewari, Kartik Hosanagar, Kashyap Deorah, 500 Startups, Blue Fog Capital',
 'Alok Bajpai, Rajnish Kumar, Amit Dey',
 'Alok Goel',
 'Alok Mittal',
 'Alok Mittal, Amit Gupta, Anuj Srivastava, Himanshu Aggarwal, Raghunandan G, Puneet Agarwal',
 'Alok Mittal, Deepak Jain, Ritesh Malik, Jim Schimdktke',
 'Alok Mittal, Zeeshan Hayat, Niraj Singh, Nikunj Jain, Anirudh Damani, Punit Goyal',
 'Alok Rawat, Grey Orange Robotics',
 'Alpha Capital',
 'Alphard Maritime Group',
 'Alteria Capital',
 'Altimeter Capital, DST Global',
 'Altimeter Capital, Sutter Hill Ventures',
 'Amadeus Capital',
 'Amajit Gupta, Praveen Dubey, J.P. Bhatt',
 'Amazon',
 'Amazon Alexa Fund & Dentsu Ventures',
 'Amazon Inc. and Mastercard',
 'Amazon, Ashish Dhawan, Catamaran Ventures, NR Narayana Murthy.',
 'Amazon, Fidelity Growth Partners, Mousse Partners',
 'Amazon, Vertex Ventures, Qualcomm, Ru-Net Technology Partners, Matrix Partners',
 'Amazon-Patni JV',
 'Ambarish Gupta, Aneesh Reddy, Bold Ventures, Vona Investments',
 'Ambit Pragma',
 'Ameera Shah, Vivek Bhargava',
 'Amen Dhyllon',
 'American Express Ventures, Sequoia Capital',
 'Amicus Capital',
 'Amit Burman, SIDBI Venture Capital',
 'Amit Choudhary',
 'Amit Choudhary, Anuj Puri',
 'Amit Gupta, Sahil Barua, Mukul Singhal, Tracxn Labs',
 'Amit Patni',
 'Amit Patni, Anirudh Damani, Samir Shah',
 'Amit Ranjan, Deepinder Goyal, Zishaan Hayath, Powai Lake Ventures',
 'Amit Ranjan, Vijay Shekhar Sharma, Kunal Bahl, Girish Mathrubootham &\\\\xc2\\\\xa0 Group of other Angel investors',
 'Amit Singhal and Unitus Seed Fund',
 'Amit Singhal, PK Gulati & others',
 'Amit Tyagi, Sandeep Acharya & others',
 'Amod Malviya',
 'Amour Infrastructure',
 'Anand Chandrasekaran',
 'Anand Chandrasekaran & Others',
 'Anand Chandrasekaran, Ananth Narayanan, Mekin Maheshwari, Ravi Garikipati, Divyesh Shah, Swastika Company Ltd',
 'Anand Chandrasekaran, Apurva Chamaria, Ritesh Malik, Ashish Toshniwal, Ajeet Khurana',
 'Anand Chandrasekaran, Kanwaljit Singh, Manoj Varghese',
 'Anand Chandrasekaran, Rajesh Sawhney, Kalpana Tatavarti, Shivanandan Pare',
 'Anand Chandrasekaran, Rajiv Mehta, Ramakant Sharma',
 'Anand Mahindra',
 'Anand Mahindra, Uday Punj, Ashish Hemrajani, Sanjeev Mehra',
 'Anand Rajaraman, Venky Harinarayan',
 'Anand Sankeshwar, Yang Shu',
 'Anand Vijay, Nipun Dureja, Satyajit Heeralal, Keith Rodricks, Gaurav Lochan, Azmul Haque, Nikhil Bagri',
 'Anand Vijay, Shashank Mehrotra & Others',
 'Aneesh Seth, Tushar Mittal',
 'AngelList, Rahul Khanna, Rajeev Arora and Ram Ramsundar.',
 'AngelPrime',
 'Anglian Omega Network',
 'Anicut Capital',
 'Anil Advani, Pramod Jain, Amrendra Reddy and Manish Satnaliwala.',
 'Anil Jain & other HNIs',
 'Anil Kapoor',
 'Anil Matai, Vikram Tandon, Shyam Sundar R & others',
 'Anil Menon',
 'Aniruddha Malpani, Startup Oasis',
 'Anirudh Damani, Daud Ali, Narendra Karnavat, Vikas Kapoor, Vikram Lakhotia, Krishna Jhunjhunwaala, Jayesh Shah',
 'Anirudh Damani, Vikram Lakhotia',
 'Anita Dongre, Yash Dongre, Milind Sarwate',
 'Ankit Gupta, Puneet Motihar',
 'Ankit Maheshwari, Anand Singh',
 'Ankit Nagori',
 'Ankur Capital',
 'Ankur Capital, Hyderabad Angels',
 'Ankur Gupta',
 'Ankush Mehta',
 'Ankush Nijhawan, Manish Dhingra, Gaurav Bhatnagar',
 'Ant Financial',
 'Ant Financial Services (Alipay)',
 'Ant Financials',
 'Anuj Puri, Redcliffe Capital, Artha India Ventures, Siddharth Kothari, Apoorv Ranjan Sharma,',
 'Anupam Mittal, Amit Gupta, Utsav Somani, Neeraj Goenka, Farooq Adam Mukadam',
 'Anupam Mittal, Anand Chandrasekaran, Uday Shankar, Chetan Bhagat',
 'Anupam Mittal, Anuj Srivastava, Ankit Nagori',
 'Anupam Mittal, Manish Vij, Prashant Tandon, Gaurav Agarwal, Akash Agarwal, Himanshu Aggarwal, Kevin Parikh',
 'Anupam Mittal, Sharad Sharma & 14 others',
 'Anurag Chauhan',
 'Aparup Sengupta, Devendra Reddy,',
 'Apis Partner, Eight Roads Ventures, Bamboo Capital Partners',
 'Apoorv Ranjan Sharma, Daud Ali and others',
 'Applyifi',
 'Aprameya Radhakrishna',
 'Aprameya Radhakrishna, Deepak Natraj, Girish Mathrubootham, Mahesh Murthy, Pallav Nadhani, Pavan Ongole, Sandeep Mathur, Vijay Shekhar Sharma & Others',
 'Aprameya Radhakrishna, Naman Sarawagi, Afsal Salu,',
 'Aqeel Ahmed',
 'Aramex Ventures Llc',
 'Arihant Patni, Avnish Mehra, Pranay Adhvaryu, Ravi Sampat',
 'Arihant Patni, RAAY Global Investments',
 'Arihant Patni, Vishal Khare,\\\\xc2\\\\xa0 Viswanath Ramachandran',
 'Arjun Handa, Amit Jindal, Nagendra Chaudhary',
 'Armat Group',
 'Artha India Ventures, Singularity Holdings, Rajan Anandan, Girish Mathrubootham',
 'Artha Venture',
 'Artiman Ventures',
 'Arun Chandra Mohan',
 'Arun Chandra Mohan, Praveen Sinha',
 'Arun Patodia, Bharat Kedia',
 'Arun Seth, T.V. Mohandas Pai, Anand Chandrasekaran, Deepak Ghaisas',
 'Arun Tadanki, Aditya Verma',
 'Ascent Capital, Kalaari Capital',
 'Ash Bhardwaj',
 'Asha Jadeja Motwani & Others',
 'Ashish Gupta',
 'Ashish Gupta and other undisclosed investors',
 'Ashish Jhalani',
 'Ashish Kacholi, S Chand Group',
 'Ashish Mahajan, Sarvesh Sharma',
 'Ashish Todi, Abhinav Patodia, Kumar Shwetabh',
 'Ashok Agarwal',
 'Ashok Goel (promoter)',
 'Ashok Kumar Gajera',
 'Ashutosh Lawania, Alok Goel & others',
 'Ashutosh Lawania, Rajul Jain, Badal Malick, Rishi Gupta & Others',
 'Ashvin Chadha',
 'Ashvin Chadha, Avtar Monga, Udaan Angels, Dheeraj Jain',
 'Asia Pacific Internet Group',
 'AskMe',
 'Aspada Advisors, IDG Ventures,\\\\xc2\\\\xa0 Inventus Capital',
 'Aspada Investment Advisors, Blume Ventures.',
 'Aspada Investment Advisors, Qualcomm Ventures',
 'Aspada Investments',
 'Aspire Logistics LLC',
 'Aspire Systems',
 'Asset Management (Asia) Ltd, Digital Garage Inc',
 'Astarc Ventures',
 'Astarc Ventures & Others',
 'Astarc Ventures, 50K Ventures & others',
 'Astarc Ventures, Anand Chandrasekaran',
 'Asuka Holdings',
 'Asuka Holdings, YouWeCan Ventures, Beenext, Beenos, M&S Partners',
 'Asuka, Pravega Ventures, BEENEXT',
 'Atul Gupta and Saurabh Rastogi',
 'Atul Ingle',
 'Atul Jain, Anil Gelra, Jaikumar Nair',
 'Atul Jalan',
 'Atul Jalan, Shrikanth & Bharath',
 'Atul Nishar',
 'Atulya Mittal',
 'Augment Ventures, Rahul Kayan, Nikhil Golcha, Shubham Gupta, Roy Kwan',
 'August Capital Partners, Michael Blakey',
 'Auxano Deals',
 'Avendus Finance',
 'Avendus Finance Pvt. Ltd',
 'Avtar Monga, chief operating office at IDFC Bank, Aditya Malik & Others',
 'Axiata Digital',
 'Axilor Ventures',
 'Axilor Ventures, E-City VEntures Atul Goel',
 'Axilor Ventures, Kumar Vembu',
 'Axilor Ventures, Newfort Capital',
 'Axilor Ventures, Parampara Early Stage Opportunities Fund & Others',
 'Axilor, Sprout Venture Partners and others',
 'Axilor, undisclosed investors',
 'Axis Capital Partners',
 'Ayesha Takia Azmi, Abu Farhan Azmi',
 'Ayushmann Khurana',
 'Azim Premji, Binny Bansal',
 'B Capital Group, Ignition Partners, Greycroft, e.ventures,\\\\xc2\\\\xa0 Eight Roads Ventures',
 'B Capital, International Finance Corporation (IFC), Accel Partners and IDG Ventures',
 'B M Gupta, Vinod Singhal',
 'B S Nagesh',
 'BAC Acquisitions, Unifi AIF, BRD Securities, Northern R Capital',
 'BCCL',
 'BEENEXT',
 'BLIP Initiatives',
 'Baillie Gifford, Falcon Edge Capital, Tiger Global, SoftBank Group, DST Global, Didi Kuaidi',
 'Balasubramanian Krishnamurthy, Sidhartha Hazarika & Others',
 'Base of Pyramid Asia (BOPA) Pte Ltd',
 'Baskar Subramanian, Saket Kumar, Gaurav Suri and Ankit Kesarwani',
 'Batlivala & Karani Securities, Venture Works',
 'Battery Road Digital Holdings LLC',
 'Bay Capital Investments and Others',
 'BedRock Ventures, Rajesh Sawhney, Shailesh Singh',
 'Bedrock Ventures',
 'BeeNext , WEH Ventures and Sprout Ventures',
 'BeeNext, TV Mohandas Pai, Kunal Shah, Sandeep Tandon',
 'Beenext',
 'Beenext, Digital Garage, Beenos, Qualgro, Mamoru Taniya, SAIF Partners',
 'Beenext, Digital Garage, Lightbox, Beenos',
 'Beerud Sheth and Ravi Mantha',
 'Bennett Coleman and Company Ltd (BCCL)',
 'Bennett, Coleman and Co. Ltd (BCCL)',
 'Bennett, Coleman and Company Ltd',
 'Bennett, Coleman and Company Ltd (BCCL),',
 'Benori Ventures LLP',
 'Bertelsmann India',
 'Bertelsmann India Investments',
 'Bertelsmann India Investments, Mayfield India, Saama Capital, India Quotient',
 'Bertelsmann India Investments, Nirvana Digital India Fund, Nirvana Digital Investment Holding, 500 Startups',
 'Bertelsmann India, Mayfield Capital, Saama Capital, Darrin Capital',
 'Bessemer Venture Partner, Accel, SAIF Partners',
 'Bessemer Venture Partners',
 'Bessemer Venture Partners and Orios Venture Partners, JM Financials and MEMG',
 'Bessemer Venture Partners, Anil Chopra',
 'Bessemer Venture Partners, Jungle Ventures, Helion Ventures',
 'Bessemer Venture Partners, Orios Venture Partners, Trifecta Capital,',
 'Bessemer Venture Partners, SAIF Partners',
 'Bessemer Venture Partners, Stellaris Venture Partners, Axis Capital, Singapore, Jungle Venture Partners',
 'Bessemer Venture Partners, Stellaris Venture Partners, Jungle Venture Partners, Axis Capital',
 'Bessemer Ventures, Blume Ventures',
 'Bessemer Ventures, Kae Capital',
 'Best Foodworks',
 'BetOnIndia Technology Pvt Ltd',
 'Bhairavi Jani, Alok Divatia, Namrata Kaul, Sohail Hashemi, Aijaz Saleem',
 'Bhanu Vikram Parsotam, Rohan Desai and Paras Patel',
 'Bharanidharan Viswanathan, Sanjiv Mittal, Shobhit Shukla, Rahul Agarwal',
 'Bharat Innovation, IDFC-Parampara Capital, Arthavida Ventures, Jitendra Gupta & Others',
 'Bhavdeep Reddy',
 'Bhavesh Manglani, Suraj Saharan, Darshan Upadhyay, Sanjay Notani & Others',
 'Bhavin Turakhia',
 'Bhavish Aggarwal, Ankit Bhati',
 'Bhavish Aggarwal, Binny Bansal,\\\\xc2\\\\xa0 Rajan Anandan, Mekin Maheshwar, Sunil Kalra, Anupam Mittal, Krishna Mehra, Singapore Angel Network',
 'Bhupen Shah, Jayesh Parekh, Sanjay Sathe',
 'Binny Bansal',
 'Binny Bansal, Anupam Mittal, Sachin Bhatia, Darius Pandole, Kunal Khattar, Dheerag Jain',
 'BitChemy Ventures, Maheshwari Investments Pvt Ltd, Anshoo Gaur, Rama Krishna Reddy, Sandeep Seerapu',
 'Bitkemy Ventures',
 'Biz Stone',
 'Biz Stone, Kunal Bahl, Rohit Bansal, Alagu Periyannan and Karthee Madasamy',
 'BlackJag Partners',
 'BlackSoil Capital Pvt Ltd',
 'BlackSoil Capital Pvt. Ltd',
 'BlackSoil Capital Pvt. Ltd.',
 'Blacksoil Capital Pvt. Ltd',
 'Blackstone Valley Group, Raghu Vohra, Aditya Dev Sood, Kamal Bansal',
 'Blinc Advisors, Amit Nanavati, Tashwinder Singh, Taranjit Jaswal, Amit Khanna',
 'Blue Orchard',
 'BlueOrchard Finance Ltd, Hinduja Leyland Finance and IntelleGrow',
 'Blume Ventures',
 'Blume Ventures & Other unnamed Investors',
 'Blume Ventures & Others',
 'Blume Ventures and RTP Global',
 'Blume Ventures, Adil Allana, Aprameya Radhakrishna, Gautam Ivatury, Signal Point Partners',
 'Blume Ventures, BEENEXT, Barkawi Holdings GmbH, TM Service Technology Holdings Gmbh, Sreevathsa Prabhakar',
 'Blume Ventures, Barkawi Holdings GmbH, TM Service Technology Holdings GmbH',
 'Blume Ventures, Contrarian Capital India Partners, Emergent Ventures India, Pallav Nadhani, Ashish Gupta, Sharad Sharma, Sirion Labs',
 'Blume Ventures, Contrarian Capital, 91springboard, Emergent Ventures, Abstract Ventures, Anthill Ventures, Axilor Ventures',
 'Blume Ventures, Flipkart',
 'Blume Ventures, Girish Mathrubootham, Aprameya Radhakrishna',
 'Blume Ventures, Goldbell Group, Anurag Srivastava, Shailesh Rao, Amiya Pathak, Rajesh Yohanan and Rahul Garg',
 'Blume Ventures, HealthQuad and Fireside Ventures',
 'Blume Ventures, IDG Ventures & Indian Angel Network',
 'Blume Ventures, Indian Angel Network',
 'Blume Ventures, Indian Angel Network, Kunal Shah, Sandeep Tandon',
 'Blume Ventures, Mumbai Angels, ah! Ventures, Digital Currency Group, Boost VC, Bank to the Future and Funders Club',
 'Blume Ventures, NB Ventures, Nspira',
 'Blume Ventures, Rajan Anandan, Sumit Jain, Aprameya Radhakrishna, Sujeet Kumar, Phanindra Sama',
 'Blume Ventures, Sachin Bansal, Vijay Shekhar Sharma, Binny Bansal,\\\\xc2\\\\xa0 Kunal Shah, Sandeep Tandon, Ashish Tulsian',
 'Blume Ventures,\\\\xc2\\\\xa0 Tracxn Labs',
 'Blume Ventures. Lenovo Capital and Incubator Group (LCIG)',
 'Blume ventures',
 'Bodhtree Consulting Limited',
 'Boman Irani, Dhruv Chitgopekar, Prantik Dasgupta',
 'BookMyShow',
 'Brand Capital',
 'Brand Capital and Others',
 'Brand Capital, Paragon Trust',
 'Brand Capital, Siddhivinayak Skyscrapers, Dinesh R. Challa',
 'Bravia Capital',
 'Breakthrough Energy Ventures',
 'Bren Corporation',
 'Brian Acton',
 'Brick Eagle',
 'Brigade Innovations LLP, TV Mohandas Pai, Suhail Rahman, Bobby Reddy, M George Oommen',
 'British and Indian Governments',
 'Broadbean Capital services',
 'ByteDance, Arun Sarin, Matrix Partners, Sequoia Capital India, Omidyar Network,\\\\xc2\\\\xa0 Falcon Edge',
 'C4D Partners',
 'CA Media LP,\\\\xc2\\\\xa0 Start Media.',
 'CASHurDRIVE Marketing Pvt Ltd',
 'CBA Capital and others',
 'CCube Angels, Frontline Strategy',
 'CDC Group Plc',
 'CDC Group plc\\\\xc2\\\\xa0',
 'CIO Angel Network',
 'CIO Angel Network (CAN)',
 'CIO Angel Network, Indian Angel Network',
 'CLP Holdings Group, Innogy, \\\\xc3\\\\x98rstead, and Tenaska',
 'CLSA Capital Partners ARIA IV Funds',
 'CMYK Health Boutique Pvt Ltd & Other individual investors',
 'CP Bothra',
 'Calcutta Angel Network, Appliyifi',
 'Calcutta Angels Network',
 'Calcutta Angels Network (CAN), Augment Ventures',
 'Calcutta Angels Network, LetsVenture, Anupam Mittal, Currae Healthtech Fund',
 'Calcutta Angels, Lead Angels & Others',
 'Calcutta Angels, Venture Nursery Angels Mumbai Angels',
 'Cameron Jones',
 'Canaan Partners',
 'Cao Yibin, Huang Wei, Madhusudan E,',
 'Capillary Technologies, Whiteboard Capital, YourNest Angel Fund, Rajul Garg',
 'CapitalG, SAIF Partners and LGT Impact Ventures',
 'CapitalG, Sequoia India',
 'CareerNet Consulting Pvt. Ltd, Ideation Initiative Pvt. Ltd,',
 'Carlyle Group, Tiger Global',
 'Carpediem Capital',
 'Carpediem Capital & Others',
 'Carrick Capital Partners',
 'Catamaran Ventures, New India Investment Corporation',
 'Cataraman Ventures',
 'Centre For Incubation & Business Acceleration (CIBA), Goa',
 'Centre for Innovation Incubation and Entrepreneurship (CIIE)',
 'CerraCap',
 'Chan Zuckerberg Initiative, Times Internet Ltd, Sequoia Capital, Sofina, Lightspeed Ventures',
 'Chandigarh Angel Network (CAN)',
 'Chandigarh Angels Funding',
 'Chandigarh Angels Network',
 'Chandigarh Angels Network (CAN)',

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [65]:
df.drop(columns='Remarks', inplace=True)

In [66]:
df.set_index('Sr No', inplace=True)

In [67]:
df.rename(columns={
    'Date dd/mm/yyyy':'date',
    'Startup Name':'startup',
    'Industry Vertical':'vertical',
    'SubVertical':'subvertical',
    'City  Location':'city',
    'Investors Name':'investors',
    'Amount in USD':'amount',
    'InvestmentnType':'round',
}, inplace=True)

In [68]:
df['amount']=df['amount'].fillna('0')
df['amount'] = df['amount'].str.replace(',','')
df['amount'] = df['amount'].str.replace('Undisclosed','0')

In [69]:
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')
df['amount']

Sr No
1       200000000.0
2         8048394.0
3        18358860.0
4         3000000.0
5         1800000.0
           ...
3040      4500000.0
3041       825000.0
3042      1500000.0
3043            0.0
3044       140000.0
Name: amount, Length: 3044, dtype: float64

In [70]:
def in_inr(dollar):
  inr = dollar*95
  return inr / 10000000

In [71]:
df['amount']=df['amount'].apply(in_inr)
df.head()

,date,startup,vertical,subvertical,city,investors,round,amount
Sr No,,,,,,,,
1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1900.000000
2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,76.459743
3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,174.409170
4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,28.500000
5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,17.100000

In [72]:
df['date']=df['date'].str.replace('05/072018','05/07/2018')
df['date']=pd.to_datetime(df['date'], errors='coerce')

In [79]:
df.columns

Index(['date', 'startup', 'vertical', 'subvertical', 'city', 'investors',
       'round', 'amount'],
      dtype='object')

In [84]:
df = df.dropna(subset=['date', 'startup', 'vertical','city', 'investors',
       'round', 'amount'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1202 entries, 1 to 2829
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         1202 non-null   datetime64[ns]
 1   startup      1202 non-null   object
 2   vertical     1202 non-null   object
 3   subvertical  890 non-null    object
 4   city         1202 non-null   object
 5   investors    1202 non-null   object
 6   round        1202 non-null   object
 7   amount       1202 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 84.5+ KB

In [85]:
df.to_csv('startup_cleaned.csv', index=False)

In [88]:
set(df['investors'].str.split(',').sum())

{'',
 'Sandeep Aggarwal',
 ' Vikrant Varshney',
 ' Ness Wadia',
 ' Bertelsmann India',
 'Pradeep Dhobale',
 'Kanwaljit Singh',
 'Altimeter Capital',
 'growX ventures',
 'Jaideep Mehta',
 ' Chandru Badrinarayanan',
 ' Helion Venture',
 ' Ruchi Narain',
 ' Dheerag Jain',
 ' Atul Nishar',
 ' Nikhil Golcha',
 'Anil Advani',
 'Amit Tyagi',
 'GHV Accelerator',
 'TV Mohandas Pai',
 'Nelstone Ventures',
 'IDG',
 'Pine Labs Pte Ltd',
 'Nederlandse Financierings-Maatschappij voor Ontwikkelingslanden N.V.',
 'Unitus Seed Fund',
 ' Sanjeev Kakkar',
 'Ideaspring Capital',
 ' Pravega Ventures',
 'Japan Vyas',
 ' Mohandas Pai',
 ' Toos N Daruvala',
 'Naspers',
 'Girish Mathrubootham',
 'Edelweiss Private Equity',
 'Quadria Capital Advisors',
 ' BeeNext',
 ' Darrin Capital',
 ' Deshe Holdings',
 ' Namrata Kaul',
 ' Aspada Ventures',
 'KCL',
 ' Niraj Singh',
 ' Individual Investors',
 ' Salil Donde',
 'Mount Nathan Advisors Pte Ltd',
 ' Venture Works',
 ' Kshitij Jain',
 'Unknown High Net-Worth Individuals',
 'Ventureast',
 ' Amit Jindal',
 ' Aditya Malik & Others',
 'Dheeraj Jain & Others',
 'Fidelity Growth Partners India',
 'Asset Management (Asia) Ltd',
 ' William Campbell',
 'Dr. Rameshwar Kumar',
 ' Rahul Garg',
 ' Qualgro',
 ' Gaurav Vats',
 'Ritesh Dwivedy',
 ' Kumar Vembu',
 'DST Global',
 ' India Internet Fund',
 'IvyCap Ventures',
 ' Piyush Shah',
 'Agnus Capital',
 'Sean O\\\\xe2\\\\x80\\\\x99Sullivan & Others',
 'Temasek Holdings',
 ' Times Internet',
 ' Sharad Sharma & 14 others',
 ' Beenextan investment fund',
 ' RWE',
 ' Qualcomm Ventures',
 '3One4 Capital',
 'Group of undisclosed Angel Investors & HNIs',
 ' Daud Ali',
 'Kunal Bajaj',
 ' MakeMyTrip',
 'Mahindra Univeg',
 ' Infuse Ventures',
 'MoMagic Technologies',
 'Microsoft Ventures',
 ' Atul Phadnis',
 ' founder and chairman of career information portal Careers360',
 ' Rohan Desai and Paras Patel',
 ' Satish Khanna and Taparia family office.',
 ' Bedrock Ventures',
 'Calcutta Angels Network (CAN)',
 'IFMR Capital Finance',
 'Infibeam',
 'Kirthiga Reddy',
 'BeeNext',
 ' Mohit Satyanand & others',
 'GEMs',
 'Orient BlackSwan',
 ' InMobi',
 'Sandeep Mathur',
 'Vinod Bansal',
 ' Rajat Gupta & Others',
 '\\\\xc2\\\\xa0 Lightbox Ventures',
 'Ankit Maheshwari',
 ' Shinji Kimura',
 ' Zishaan Hayath',
 ' Jason Hirschhorn',
 ' Ankush Gupta',
 ' Fenqile',
 ' Nirvana Digital Investment Holding Co Ltd',
 'Sistema Asia Fund',
 'Viraj Tyagi & Others',
 'India Ventures',
 ' Amit Nanavati',
 'Infosys co-founder Kris Gopalakrishnan',
 'National Science and Technology Entrepreneurship Development Board',
 'Lightspeed Venture Partners',
 ' Jim Schimdktke',
 'Avendus Finance Pvt. Ltd',
 ' SCM Holdings',
 '\\\\xc2\\\\xa0 Ruchi Sanghvi & Others',
 'SIDBI',
 'Indian Angel Network',
 ' RNT Capital',
 ' Nikhil Bagri',
 ' Fauzan Rahim',
 ' Burda Principal Investments',
 'Quikr',
 'Sarath Sura',
 'Amadeus Capital',
 ' Berggruen Holdings',
 'Nihon Kotsu',
 'ChrysCapital',
 ' Arkas Industries',
 'Matt Glickman',
 ' Keshav Sanghi',
 ' Seedfund',
 'Hinduja family',
 'Constellation Technology Ventures (Exelon Corporation)',
 'Morgan Stanley Private Equity Asia',
 'Rajul Garg & Others',
 ' Pavan Ongole',
 ' RB investments & Others',
 'Aramex Ventures Llc',
 ' Pavan Bakeri',
 ' Villgro',
 'SQue Capital',
 'CapitalG',
 ' Zop Smart',
 ' Vy Capital',
 'CBA Capital and others',
 'Stripes Group',
 'Iron Pillar',
 'Factor[e] Ventures',
 'Zodius Technology Fund',
 'havya Sharma',
 'The Chennai Angels',
 'Temasek',
 'Times Internet Ltd',
 ' GrowX Ventures',
 'Anurag Chauhan',
 ' Pramod Bhasin',
 'Exfinity Venture',
 'Titan Co Ltd',
 ' Siddharth Pai',
 'Lalitesh Katragadda',
 ' Barkawi Holdings GmbH',
 'Rebright Partners',
 ' Krishna Mehra',
 ' Accel Partners & Others',
 ' Manickam Mahalingam',
 'Neha Vats',
 ' CSC Upshot & Angel investors',
 'Mumbai Angels',
 'Sequoia and Kalaari Capital.',
 ' Mohit Gupta',
 ' Sunil Koul',
 'Fork Media',
 'Dinesh Agarwal',
 'High Networth Individuals from India & USA',
 ' Mumbai Angels Network',
 'Munesh Khanna',
 ' Sushill Jiwarajka',
 'WaterBridge Ventures',
 ' Sharad Sharma',
 'Paytm',
 ' Lightbox',
 ' Vindi Banga',
 'Wingify',
 ' Vaibhav Jain',
 'Zaffiro Ventures',
 'Flipkart',
 ' Investopad',
 ' Hero Enterprise',
 'Prime Venture Partners',
 ' Others',
 ' Bharat Kedia',
 'Karanpal Singh',
 'Riqueza Capital',
 'Maheshwar Peri',
 'Rohan Agila',
 ' Mr. Praveen Someshwar',
 'Chandralekha Construction Pvt. Ltd.',
 ' Internet Group',
 ' Kalaari Capital',
 'Bren Corporation',
 ' Gaurav Lochan',
 ' Digital Garage Inc',
 ' Huang Wei',
 'Base of Pyramid Asia (BOPA) Pte Ltd',
 'Vineet Singh',
 'KDDI\\\\xc2\\\\xa0',
 'Village Capital',
 'Rainmatter',
 ' Lightspeed Venture Partners',
 'International Finance Corp',
 'Helion Venture Partner',
 'Jasper Infotech Pvt Ltd',
 'Peepul Capital',
 'Kashyap Deorah',
 ' Horseferry',
 ' Russian venture capital fund Ru-Net',
 ' Govind Rajan & Others',
 ' Sanjay Sathe',
 'R M Picture Company Pvt. Ltd.',
 ' Greenoaks Capital',
 ' Venk Krishnan',
 'Vedanta Capital',
 ' Catamaran Ventures',
 'Carpediem Capital',
 'Rothenberg Ventures',
 'WRV Capital',
 ' Jagdish Kumar',
 'ThinQbate',
 '\\\\xc2\\\\xa0 Abhishek Jain',
 ' Simile Ventures',
 ' Dileep Nath',
 'International Finance Corporation (IFC)',
 'Sequoia Capital India',
 'TIW Private Equity',
 'Nandan Nilekani',
 'Marico Innovation Foundation (MIF)',
 ' Sunil Kalra',
 'State Street Global Advisors',
 'Quotient',
 'Times Internet',
 'Frontline Strategy',
 'Vinod Martin',
 'Lighthouse',
 ' Vivek Bhargava',
 ' AVN Business Solutions',
 'Unitus Ventures',
 ' Mariwala family',
 ' Vikram Sud',
 'Lakshmi Vilas Bank & undisclosed HNIs',
 'Axiata Digital',
 'Arihant Patni',
 ' 500 Start-Ups',
 'India Quotient & other investors',
 ' Accel Partners and IDG Ventures',
 'Oman India Joint Investment Fund (OIJIF)',
 'CIO Angel Network (CAN)',
 ' Anirudh Damani',
 ' Ashish Gupta',
 'Atulya Mittal',
 ' IDG Ventures India',
 ' Vinod Jain & Others',
 ' Mayank Singhal',
 ' iSON',
 'IvyCamp Ventures',
 ' Arjun Mehta',
 'Ctrip.com International Ltd',
 'Reliance Capital Venture',
 'Alok Mittal',
 'General Atlantic',
 ' Rajesh Ranavat',
 ' Dreamweaver Investments',
 'Naveen Arya',
 ' Pablo van den Bosch & Others',
 ' AET Fund',
 'JM Financial Products Ltd',
 'Pravin Agarwala & others',
 ' Dinesh Kundu & others',
 ' Ascent Capital',
 ' Dalip Pathak',
 ' Hrishi Oberoi',
 'Helion Ventures',
 'Mahendra Patel',
 'Sunil Mehta',
 ' Romulus Capital and Kalaari Capital',
 ' Sixth Sense',
 ' Sidharth Pansari',
 ' Vaibhav Vohra',
 ' Kunal Shah & Sandeep Tandon',
 'Insight Partners',
 'Aegon NV',
 ' Mandhian family & Others',
 'Mato Peric',
 'S.Gopalakrishnan',
 ' Alphabet\\\\xe2\\\\x80\\\\x99s growth investment arm Capital G and Axis Bank',
 'Sachin Tendulkar',
 'Vijay Shekhar Sharma',
 ' Rajesh Arora',
 ' Valiant Capital',
 ' Apoorva Patni',
 'Existing Investors',
 'Bennett Coleman and Company Ltd (BCCL)',
 'Multipoint Capital',
 ' Paragon Partners',
 'Ranjan Pai',
 'Lohia Group',
 'Creation Investments Capital Management',
 ' Shunwei Capital',
 'Jayant Humbarwadi',
 ' Singapore Angel Network & Aseem Vadehra',
 'Matrix Partner',
 ' Y Combinator and Venture Highway',
 ' Kapil Hetamsaria',
 'T V Mohandas Pai',
 'Helion Venture Partners',
 'Sachin Bhatia',
 ' Hillhouse Capital',
 'Mayfield Fund',
 'Justin Kan',
 ' Ruchi Sanghvi & others',
 'Newbie Promoter Pvt Ltd',
 ' Harmony Partners',
 'DTDC Express Ltd',
 'Z Nation Lab',
 'IDG ventures',
 'undisclosed investors',
 ' Nikunj Jhaveri',
 'Ganesh Natarajan',
 ' Sandeep Singh',
 'Natarajan Iyer',
 ' Excelsior Investments',
 ' Siddharth Banerjee',
 ' Inc',
 'MASSIF',
 'Eight Roads Ventures India',
 'CerraCap',
 ' Abhishekh Goyal',
 'Kedar Lele',
 'Nalin Jain',
 ' Sixth Sense Ventures',
 ' R Ramaraj',
 ' Pramod Jain',
 ' Foxconn',
 ' Ajay Bhatia',
 'TVS Automobile Solutions Ltd',
 'Saama Capital',
 'Gujarat Venture Finance Limited (GVFL)',
 ' Tarun Khandelwal',
 ' Susquehanna International Group.\\\\xc2\\\\xa0 Wavemaker Partners',
 ' Tushar Mittal',
 'SIDBI Venture Capital Ltd',
 'Green House Ventures (GHV)',
 'Mirah Hospitality',
 'Tekne Capital Management',
 ' Sandeep Acharya & others',
 'Warburg Pincus',
 ' Vishal Khare',
 'Sixth Sense Ventures',
 'Rajasthan Angel Investor Network',
 ' Mape Advisory Group',
 'Nazara Games',
 ' Gautam Gandhi',
 ' American Express Ventures',
 'Mayfield',
 'IFMR Capital',
 'Anuj Puri',
 'Brand Capital',
 'The Saha Fund',
 ' Yuri Milner',
 ' VC firms India Quotient and Kae Capital',
 'Bhupen Shah',
 ' TCI Ventures',
 'Insignia Ventures Partners',
 'Ravi Linganuri',
 ' Multiples Alternate Asset Management',
 'Raghunandan G',
 'LetsVenture',
 ' Ramakant Sharma',
 'Lashit Sanghvi',
 'PurpleTalk Inc',
 'Deepak Nathani',
 ' Vispi Daver',
 'pi Ventures',
 'Mayfield India',
 'Promatus Group',
 'Lightbox Ventures',
 'Amit Choudhary',
 'Undisclosed Investor',
 'Sanjeev Kapoor',
 'Future Fund',
 ' Vikas Ranjan',
 'Ramesh Jogani',
 'DMG Information',
 'Rajesh Sawheny ',
 'Undisclosed angel investors',
 'Anand Chandrasekaran',
 'Nitin Passi',
 'Radhakrishnan Natarajan & Others',
 ' IDG Ventures',
 ' Anuj Gupta',
 'Phanindra Sama',
 '\\\\xc2\\\\xa0 Viswanath Ramachandran',
 'Harsh Mahajan',
 ' Tandem Capital',
 ' Vikram Chachra',
 'Rohitash Gupta',
 ' Endiya Partners',
 ' Fred Khosravi',
 ' Keith Rodricks',
 ' Accel Partners and G Raghunandan',
 ' Empire Angels',
 'Mangroves Capital Partners',
 '\\\\xc2\\\\xa0 Nirvana Ventures Advisors',
 ' Saha fund Partners',
 ' Ravikanth Reddy',
 ' The HR Fund',
 ' Sumit Jain',
 'Blume Ventures and RTP Global',
 'Vishal Bali',
 'Baskar Subramanian',
 ' India Quotient',
 '\\\\xc2\\\\xa0 Ganayantrika Systems',
 'Pankaj Chopra',
 'Saama Capital and DSG Consumer Partners',
 ' Tarun Adlakha',
 ' Mustafa Patni',
 ' Singapore Angel Network',
 'Nimit Panigrahi',
 ' Big Data Investments B.V',
 ' Shripad Nadkarni',
 'Subodh Gupta',
 'Sequoia India',
 'Green House Ventures',
 ' Saurabh Srivastava',
 ' Sandeep Tandon',
 ' Aneesh Reddy',
 ' Michael & Susan Dell Foundation',
 'Fosun International',
 ' Aarin Capital & Others',
 ' Sequoia India',
 ' Priti Padhy',
 ' Sands Capital and International Finance Corporation',
 'Private Sector Banks (Debt Funding)',
 ' Darshan Upadhyay',
 ' Dr Paresh Doshi',
 'Geniee',
 ' Rohit MA',
 'HDFC Life',
 ' Nilender Chauhan',
 ' Gaurav Dalmia',
 ' Softbank',
 ' Sunil Goyal Ashish Gupta',
 ' Parmeshwar Sharma',
 'Aavishkaar Venture Management',
 'Khattar Holdings',
 'Nexus Venture Partners',
 'Chirag Nikunj Sheth & Others',
 ' Y Combinator',
 'Sanjiv Rai',
 ' Rohit Jain',
 '1Crowd (through crowdfunding)',
 'Cherry Tin',
 'CDC Group Plc',
 ' Vishal Gondal',
 'Satya D Sinha',
 ' Ashvin Chadha',
 'Axilor',
 'ah! Ventures',
 ' Flipkart',
 'IDG Ventures India',
 ' Maiden Lane Ventures',
 ' Nazara Technologies',
 ' Arun Garg',
 'Investors from Mumbai Angels & LetsVenture',
 ' Yogesh Andlay',
 'Ash Bhardwaj',
 ' MeraEvents.',
 ' Innogy',
 ' MJ Aravind',
 ' Gaurav Sharma',
 ' Raghunandan G',
 ' Zoya Akhtar',
 'Gopal Aggarwal',
 'Omphalos Ventures India LLP',
 ' Ananda Kallugadde',
 ' Dr. Aniruddha Malpani',
 'Alok Rawat',
 '500 Startups',
 'Verlinvest SA',
 ' Axilor Ventures',
 ' ABCOM Investments',
 ' Nyca Partners and Thomvest Ventures',
 'IDG Ventures',
 'Silicon Valley Ventures',
 ' Ashneer Grover',
 'Delhivery',
 ' Qasar Younis',
 'Binny Bansal',
 '3one4 Capital',
 ' Aprameya Radhakrishna',
 ' Leo Wang Sangeeth Ram',
 ' Brand Capital',
 ' Arihant Patni of Patni Family Office',
 ' Nexus Venture Partners',
 ' K Ganesh',
 ' AdvantEdge Partners',
 ' Mridul Upreti',
 '\\\\xc2\\\\xa0 Smart Start Fund; Kunal Shah',
 ' Sequoia Capital Global Equities',
 'Gleevoaz Ventures',
 'Ivycap Ventures Advisors',
 '\\\\xc2\\\\xa0 & other Angel investors.',
 'Emerging India',
 ' Satya Muthyala',
 ' director at Byramjee Jeejeebhoy Pvt. Ltd were among the angels',
 ' Parekh Marine Transport',
 'Luxasia Group',
 'Group of 15 Angel Investors',
 'GirnarSoft',
 'British and Indian Governments',
 ' Globeinvestor',
 ' Aaruha Technology Fund',
 ' Fidelity Growth Partners India',
 ' Anupam Tyagi',
 ' IMJ Investment Partners',
 ' Adveq Management',
 ' Tiger Global',
 'Ashish Jhalani',
 'Tata Capital Innovation Fund',
 ' RippleWave',
 ' Ritesh Malik',
 'Digital Garage',
 ' Orios Venture Partners',
 ' Kunal Shah',
 ' Anisha Mittal',
 'Fundamentum',
 '\\\\xc2\\\\xa0 Aarin Capital',
 'Das Capital',
 'Falcon Edge Capital',
 ' MAPE Advisory Group',
 'Goldman Sachs',
 'Uniqorn ventures',
 ' Nirvana Digital India Fund',
 ' Exfinity Ventures',
 '\\\\xc2\\\\xa0 Rahul Chawla',
 ' Sanjay Shenoy',
 ' ru-Net',
 ' Mohit Satyan',
 ' Mayfield',
 ' Space Matrix',
 'Shunwei Capital',
 'IAN Fund',
 'DHI Group Inc',
 'Songhyun Investment',
 ' Vinay Mittal',
 ' Arihant Patni',
 ' Balamurugan Mani',
 ' Roy Kwan',
 ' Susa Ventures',
 'Shaan',
 ' Darius Pandole',
 ' Dr. Apoorv Ranjan Sharma',
 ' Jungle Ventures & Bessemer Venture Partners',
 'Labruyere Eberl\\\\xc3\\\\xa9',
 ' Amereus Group',
 'AJ Ventures and Jain International Trade Organisation (JITO)',
 ' LN Buddharaju',
 ' Zaheer Memon',
 'Sharad Sharma',
 ' Anoop Hingorani',
 'Unicorn India Ventures',
 'Anicut Capital',
 'India Educational Investment Fund',
 ' Axis Capital',
 ' Deepak Sharma',
 'Powai Lake Ventures',
 'QPrize from Qualcomm Ventures',
 'Sunrise Capital GmBH',
 ' Sreepathy Viswanathan',
 'Ingram Content Group',
 ' Venture Highway',
 'Florida based Angel investor',
 'Bessemer Venture Partners',
 'Impanix Capital',
 'Centre for Innovation Incubation and Entrepreneurship (CIIE)',
 ' and Ajai Chowdhry',
 ' Indus Age Partners',
 ' Salesforce Ventures',
 'Subhkam Ventures and Mohit Khadaria',
 ' Times Internet Ltd',
 'Vellayan Subbiah',
 'BedRock Ventures',
 'Extreme Venture Partners\\\\xc2\\\\xa0 William Bissell',
 'Korea Investment Partners (KIP)',
 ' Hermes Group',
 ' Anand Sankeshwar',
 ' Rohit Bansal',
 ' Viswanath Ramachandran',
 'Falcon Edge',
 ' Rajesh K Murthy',
 'Claris Capital',
 'Gati Ltd',
 ' Leon Seynave',
 'Quintillion Media',
 ' Arun Khanna',
 'Mark Mobius & 9 Other Angel investors',
 'VentureNursery',
 ' Bennett Coleman & Co. Ltd',
 'Horizons Ventures',
 ' Arjun Sharmaa',
 'DSG Consumer Partners',
 ' Sarvesh Sharma',
 ' \\\\xc3\\\\x98rstead',
 ' Jungle Venture Partners',
 ' Himanshu Aggrawal',
 'Pankaj Gupta',
 'Mohit Gulati',
 ' Indian Angel Network',
 ' Sumit Dayal and others',
 'Snow Leopard',
 'India Quotient',
 'Grex.in',
 'Singapore Angel Network',
 'Kemark Ventures',
 ' NGP',
 'BCCL',
 'HIS Co. Ltd',
 'Franchise India',
 ' Arvind Uppal',
 'Dr Ramesh Ayyala',
 ' Syngenta AG',
 '\\\\xc2\\\\xa0 Lumis Partners',
 ' Tiger Global Management',
 'Venturra Capital',
 'Softbank',
 'India Nivesh Growth Fund',
 'Anita Dongre',
 'MeritTrac',
 ' Sonu Bhasin',
 'Alpha Capital',
 '\\\\xc2\\\\xa0 Ravi Saxena & Others',
 ' CDC Group',
 ' Abstract Ventures',
 'Hyderabad based investor',
 ' EDBI',
 'Mohandas Pai & others',
 ' Nandan Nilekani\\\\xe2\\\\x80\\\\x99s NRJN Trust',
 ' Jay Srinivasan',
 'William Bissel',
 'GrowthStory',
 ' Prashant Malik and others',
 'Composite Capital Management',
 ' Partech Ventures',
 'Tiger Global',
 ' Mistletoe',
 'Vipul Parekh',
 'Vishwadeep Bajaj',
 'AVG Group',
 ' Shireesh Palle',
 'Vinod Khatumal',
 ' Subramanya SV',
 'Rattan Chadha',
 'Bessemer Venture',
 'NB Ventures',
 'Cao Yibin',
 'RB Investments',
 'Mahesh Parasuraman',
 ' Avtar Monga',
 ' Uday Kotak',
 ' Altimeter Capital',
 '\\\\xc2\\\\xa0 Ralph Berezan',
 'Asuka Holdings',
 ' Anand Ladsariya',
 'Naveen Tewari',
 ' Shailesh Rao',
 'Varun Ahuja',
 ' Singularity Holdings',
 ' TNN Capital and others',
 'MDI Ventures & Telkom Indonesia',
 ' Nicolas Braithwaite',
 'Myntra/LivSpace Founders',
 'Mumbai Angels Network',
 'Sanjay Sethi',
 'Parampara Capital',
 ' Moksh Sports Ventures',
 ' Sparknext',
 'Sprout Angels',
 ' Nirmal Singh',
 'Vidyadhar Sarfare',
 'Manipal Education and Medical Group (MEMG)',
 'Snow Leopard Technology Ventures',
 'Anand Mahindra',
 ' Alok Divatia',
 ' Emergent Ventures',
 'Westbridge Capital Partners',
 ' a Dutch government fund',
 'Venugopal Dhoot',
 'Arun Seth',
 'A M Sikander',
 'Siddhartha Gupta',
 'Sabre Partners',
 ' T.V. Mohandas Pai',
 ' TPG Growth',
 ' Blume Ventures & IvyCap Ventures',
 ' Milind Sarwate',
 ' Shubham Gupta',
 ' BEENEXT',
 ' Contrarian Capital',
 'Ankush Nijhawan',
 'Aarin Capital Partners',
 'Alex Chua',
 ' Hinduja Group',
 'Paytm (One97 communications)',
 ' Udaan Angels',
 ' Samih Toukan and Hussam Khoury',
 ' Lightspeed India',
 '\\\\xc2\\\\xa0 Lok Capital',
 'International Finance Corporation',
 ' LetsVenture',
 'Langoor',
 ' Amit Nagar',
 ' Rakesh Malhotra',
 'Ajai Chowdhry',
 'Anupam Mittal',
 ' Sanjay Mehta & Others',
 'High Networth Individuals (undisclosed)',
 ' Capricorn Investment and IFC',
 ' Suresh Shankar',
 ' V Balakrishnan',
 'HT Media',
 ' Waterbridge Ventures and ThinKuvate',
 'Bhairavi Jani',
 'Steadview Capital and Vy Capital.',
 ' Vikas Kapoor',
 ' Pranav Pai',
 'undisclosed investor',
 'Artiman Ventures',
 'Dutch government fund',
 ' Mayfield & Others',
 'Srinivas Tirupati',
 ' Draper Associates',
 ' Amrish Rau',
 'Reliance Corporate Advisory Services Ltd',
 'Startup Buddy',
 ' Dr. Ranjan Pai',
 'Aakrit Vaish',
 ' Ankur Warikoo',
 ' Zodius Technology Opportunities Fund',
 ' Manish Dhingra',
 ' Riddhesh Gandhi & Others',
 'Google',
 'Al Dhaheri family',
 'Dheeraj Jain',
 'Harsh Mariwala',
 'B M Gupta',
 'Raman Roy',
 '\\\\xc2\\\\xa0 Mohit Saxena',
 'Noshir Kaka',
 'SF Capital Group',
 ' Sol Primero',
 ' YouWeCan Ventures',
 'Shopclues',
 'Ameera Shah',
 ' Elevar Equity',
 'Michael & Susan Dell Foundation',
 'Sequoia Capital India Advisors',
 'Rudy Gopalakrishnan',
 'Ajit Surana',
 ' Kanchan Ghoshal',
 ' Narayan Seshadri',
 'Triodos Investment Management',
 ' Jayant Davar',
 ' Ram Kumar Kakani',
 'Emerald Media',
 'Aqeel Ahmed',
 'Prasid Uno Family Trust',
 ' R Balachandar',
 ' and Jamshed Jeejeebhoy',
 'Roopak Saluja',
 ' Axan Venture',
 ' Unitus Seed Fund',
 ' American Express',
 ' Hetal Sonpal',
 'Triton Investment Advisors',
 ' Florintree Advisors',
 ' YourNest Angel Fund',
 ' Cyber Carrier VC',
 ' Prathithi Investment Trust',
 'R. Jayakumar',
 ' Greycroft Partners',
 ' Others from LetsVenture',
 'Manish Kheterpal',
 'Jaarvis Accelerator',
 'Paragon Partners',
 ' Michael Marks',
 'Artha Venture',
 'Cismat Cargo Services Pvt. Ltd.',
 ' ah! Ventures',
 'GBIM Technologies Pvt Ltd',
 'Segnel Venture',
 ' Vinners',
 ' Helion Venture Partners',
 ' Omidyar Network and Kaizen Private Equity also participated in the round',
 'Anglian Omega Network',
 ' Steven Lurie',
 ' Swapan Rajdev',
 'SC GG India Mobility Holdings LLC',
 'Earlsfield Capital',
 'Sachin Dalal',
 ' Sanjay Mehta',
 'Grace Grace Techno Ventures LLP',
 'Raj Gala Shah',
 ' Sprout Capital',
 ' Gaurav Suri and Ankit Kesarwani',
 'Grasshoppers',
 'Kludein LLC\\\\nPhanindra Sama',
 'Ajeet Khurana Jinesh Shah',
 ' Rahul Gautam & Others',
 'Mistletoe',
 ' Behram Vakil and Jerxis Vandrevala',
 '\\\\xc2\\\\xa0 Lightspeed India',
 'Rakesh Gupta',
 'Sathguru Catalyzer Advisors',
 'Inflexionpoint',
 ' Frontline Strategy',
 'Aspada Investment Advisors',
 ' Lightspeed Ventures',
 ' Amit Manocha',
 ' Trifecta Capital',
 'Undisclosed investors',
 ' BizReach',
 ' Quilvest',
 'Alibaba',
 ' Accel Partners and Saama Capital',
 'Lensbridge Capital',
 'Acumen Fund',
 ' Deepak Ghaisas',
 ' Axon Partners',
 ' Sudhir Anandarao',
 'Atul Nishar',
 ' Gyanendra Singh',
 ' MediaTek',
 ' Mohit Agarwal',
 'SBI (Stand Up India Scheme)',
 'Stellaris Ventures & Others',
 ' Appliyifi',
 ' Harvard Angels',
 'PremjiInvest',
 ' Binny Bansal',
 'Eight Road Ventures',
 'Deepak Kulkarni',
 'Daman Soni',
 ' Sahil Barua',
 'TracxnLabs',
 ' Nirav Choksi & Others',
 ' Aspada',
 ' Tashwinder Singh',
 ' Aditya Aggarwal',
 'Undisclosed Japanese investor',
 'WestBridge Capital',
 ' Sailender Solanki',
 'Asuka',
 ' Emergent Ventures India',
 'Kalaari Capital',
 'ZigExN',
 'Prashant Puri',
 'SoftBank Group Corp',
 'JSW Ventures',