In [47]:
import pandas as pd
import requests

In [48]:
response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=7c5774dfa4a21b5e2c31126ada7daa1c&language=en-US&page=1')

df_products = pd.DataFrame(response.json()['results']) [['id', 'title', 'popularity', 'release_date', 'vote_average', 'vote_count']]
df_products.head(2)

,id,title,popularity,release_date,vote_average,vote_count
0,969681,Spider-Man: Brand New Day,2011.4042,2026-07-28,7.989,843
1,1368337,The Odyssey,1053.6131,2026-07-15,7.950,2147

In [49]:
all_pages_data = []

In [51]:
for i in range(1, 429):
    response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=7c5774dfa4a21b5e2c31126ada7daa1c&language=en-US&page={}'.format(i))
    temp = pd.DataFrame(response.json()['results'])[['id', 'title', 'popularity', 'release_date', 'vote_average', 'vote_count']]
    all_pages_data.append(temp)


df = pd.concat(all_pages_data, ignore_index=True)
df

,id,title,popularity,release_date,vote_average,vote_count
0,969681,Spider-Man: Brand New Day,2011.4042,2026-07-28,7.989,843
1,1368337,The Odyssey,1053.6131,2026-07-15,7.950,2147
2,1081003,Supergirl,497.4835,2026-06-24,6.739,1491
3,634649,Spider-Man: No Way Home,487.6625,2021-12-15,7.935,22449
4,454639,Masters of the Universe,393.7220,2026-06-03,7.274,1544
...,...,...,...,...,...,...
15735,1303319,Baobab,3.5486,2024-06-16,0.000,0
15736,824977,The Hatters Jubilee Concert: Live at the Litse...,4.3159,2021-04-19,6.200,2
15737,675319,Zone 414,4.8573,2021-09-03,5.311,307
15738,515158,Lily Bily,3.7616,2018-04-13,0.000,0
15739,1447501,Arrudas Boulevard,4.0811,2026-03-18,0.000,0

In [53]:
df.shape

(15740, 6)

In [54]:
df.to_csv('tmdb_movies.csv')